global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "python_app"
    static_configs:
      - targets: ["python_app:8000"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres_exporter:9187"]
